name: C++ CI Pipeline

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake libopencv-dev wget tar

      - name: Download OnnxRuntime
        run: bash scripts/setup_onnx_deps.sh

      - name: Configure and Build
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=DEBUG -DBUILD_TESTS=ON
          cmake --build build

      - name: Run Unit Tests
        run: |
          cd build
          ctest --output-on-failure

